
% Copyright 2020 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Rajat Dipta Biswas
%                rdbiswas97@gmail.com

function [ b_out ] = Utrsv_unb_var1( U, b )

    [ UTL, UTR, ...
      UBL, UBR ] = FLA_Part_2x2( U, ...
                                 0, 0, 'FLA_BR' );
  
    [ bT, ...
      bB ] = FLA_Part_2x1( b, ...
                           0, 'FLA_BOTTOM' );
  
    while ( size( UBR, 1 ) < size( U, 1 ) )
  
      [ U00,  u01,       U02,  ...
        u10t, upsilon11, u12t, ...
        U20,  u21,       U22 ] = FLA_Repart_2x2_to_3x3( UTL, UTR, ...
                                                        UBL, UBR, ...
                                                        1, 1, 'FLA_TL' );
  
      [ b0, ...
        beta1, ...
        b2 ] = FLA_Repart_2x1_to_3x1( bT, ...
                                      bB, ...
                                      1, 'FLA_TOP' );
  
      %------------------------------------------------------------%
  
      %                       update line 1                        %
      %                             :                              %
      %                       update line n                        %
  
      beta1 = laff_dots( -1 * u12t, b2, beta1 );
      beta1 = beta1 / upsilon11;

      %------------------------------------------------------------%
  
      [ UTL, UTR, ...
        UBL, UBR ] = FLA_Cont_with_3x3_to_2x2( U00,  u01,       U02,  ...
                                               u10t, upsilon11, u12t, ...
                                               U20,  u21,       U22, ...
                                               'FLA_BR' );
  
      [ bT, ...
        bB ] = FLA_Cont_with_3x1_to_2x1( b0, ...
                                         beta1, ...
                                         b2, ...
                                         'FLA_BOTTOM' );
  
    end
  
    b_out = [ bT
              bB ];
  
  return
  