
% Copyright 2020 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Rajat Dipta Biswas
%                rdbiswas97@gmail.com

function [ y_out ] = Trmvp_ut_unb_var1( U, x, y )

    [ UTL, UTR, ...
      UBL, UBR ] = FLA_Part_2x2( U, ...
                                 0, 0, 'FLA_BR' );
  
    [ xT, ...
      xB ] = FLA_Part_2x1( x, ...
                           0, 'FLA_BOTTOM' );
  
    [ yT, ...
      yB ] = FLA_Part_2x1( y, ...
                           0, 'FLA_BOTTOM' );
  
    while ( size( UBR, 1 ) < size( U, 1 ) )
  
      [ U00,  u01,       U02,  ...
        u10t, upsilon11, u12t, ...
        U20,  u21,       U22 ] = FLA_Repart_2x2_to_3x3( UTL, UTR, ...
                                                        UBL, UBR, ...
                                                        1, 1, 'FLA_TL' );
  
      [ x0, ...
        chi1, ...
        x2 ] = FLA_Repart_2x1_to_3x1( xT, ...
                                      xB, ...
                                      1, 'FLA_TOP' );
  
      [ y0, ...
        psi1, ...
        y2 ] = FLA_Repart_2x1_to_3x1( yT, ...
                                      yB, ...
                                      1, 'FLA_TOP' );
  
      %------------------------------------------------------------%
  
      %                       update line 1                        %
      %                             :                              %
      %                       update line n                        %
  
      psi1 = laff_dots(chi1, upsilon11, psi1);
      psi1 = laff_dots(x0, u01, psi1);

      %------------------------------------------------------------%
  
      [ UTL, UTR, ...
        UBL, UBR ] = FLA_Cont_with_3x3_to_2x2( U00,  u01,       U02,  ...
                                               u10t, upsilon11, u12t, ...
                                               U20,  u21,       U22, ...
                                               'FLA_BR' );
  
      [ xT, ...
        xB ] = FLA_Cont_with_3x1_to_2x1( x0, ...
                                         chi1, ...
                                         x2, ...
                                         'FLA_BOTTOM' );
  
      [ yT, ...
        yB ] = FLA_Cont_with_3x1_to_2x1( y0, ...
                                         psi1, ...
                                         y2, ...
                                         'FLA_BOTTOM' );
  
    end
  
    y_out = [ yT
              yB ];
  
  return
  